services:
  app:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        PHP_VERSION: ${PHP_VERSION:-8.4}
    container_name: ${COMPOSE_PROJECT_NAME:-wp-settings-framework}-php
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../:/app
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    tty: true
    stdin_open: true
    networks:
      - wp-settings-framework

networks:
  wp-settings-framework:
    driver: bridge
